permalink: /:categories/:title/
url: "http://lllsycom.com"
full_name: "LLLsyCom"
first_name: "Just"
last_name: "Me"
blog_title: "LLLsyCom"
author_img_name_path: "/images/users/user.jpg"
disqus_shortname: "lllsycom"
copyright_year: "2016"
google_analytics_code: ""
aboutme: "Enjoy your life"
